lib/fatex_web/router.ex
defmodule FatexWeb.Router do
  use FatexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug FatexWeb.Plug.GenerateCSRF
  end

  pipeline :authenticate do
    plug FatexWeb.Plug.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FatexWeb do
    pipe_through :browser

    resources "/user", UserController, only: [:new, :create]
    resources "/login", LoginController, only: [:new, :create]
  end

  scope "/", FatexWeb do
    pipe_through :browser
    pipe_through :authenticate

    # User create/update screens
    resources "/user", UserController, only: [:edit, :update]
    
    # Login screen
    # FIXME: dont find how to make a post thought the live_view
    # resources "/login", LoginController, only: [:delete]
    get "/login", LoginController, :delete

    # Send PDF to client
    get "/file/:model_id/:render_id", FileController, :get

    # Figures upload and list
    resources "/uploads/:model_id", UploadController, only: [:create]

    # Share Controller
    resources "/model_share", ModelShareController, only: [:show, :create]
    get "/model_share/:model_id/:shared_user_id", ModelShareController, :delete

    # LiveView screens and sub-screens
    live "/", HomeLive, session: [:user_id]
    live "/model/:model_id", ModelLive, session: [:user_id, :csrf_token]
    live "/model-list/:user_id", ModelListLive, session: [:user_id]
    live "/step", StepLive, session: [:step_id] 
    live "/section", SectionLive, session: [:root_section_id]
    live "/menu", MenuLive, session: [:step_id, :user_id, :csrf_token]
  end
end

lib/fatex/accounts/user.ex
defmodule Fatex.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Fatex.LatexConfigs.Model
  alias Fatex.Accounts.SharedModel

  schema "users" do
    field :email, :string
    field :name, :string
    field :password, :string, virtual: true
    field :password_hash, :string

    has_many(:models, Model) 
    has_many(:shared_models, SharedModel) 
    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email, :password])
    |> validate_required([:name, :email, :password])
  end

  @doc false
  def registration_changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email, :password])
    |> validate_required([:name, :email, :password])
    |> put_pass_hash()
  end

  defp put_pass_hash(%Ecto.Changeset{valid?: true, changes: %{password: pass}} = changeset) do
    put_change(changeset, :password_hash, Argon2.add_hash(pass)[:password_hash])
  end
  defp put_pass_hash(changeset), do: changeset
end

lib/fatex_web/controllers/user_controller.ex
defmodule FatexWeb.UserController do
  use FatexWeb, :controller
  alias Fatex.Accounts
  require Logger

  # show create user
  def new(conn, _params) do
    changeset = Accounts.change_user()
    render(conn, "new.html", changeset: changeset)
  end

  # create user
  def create(conn, %{"user" => user}) do
    case Accounts.create_user(user) do
      {:ok, user} ->
        conn
        |> FatexWeb.Auth.login(user)
        |> redirect(to: "/")

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  # show update user
  # Ignore the id, for security reasons, use the sesson 
  def edit(conn, %{"id" => _id}) do
    user = conn.assigns.current_user
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", changeset: changeset, user_id: user.id)
  end

  defp update_user(conn, user, old_pass, params) do
    case Accounts.verify_user(user, old_pass) do
      true ->
        Accounts.update_user(user, params)
        redirect(conn, to: "/")

      false ->
        conn
        |> put_flash(:error, "Invalid password")
        |> render("edit.html", changeset: Accounts.change_user(user), user_id: user.id)
    end
  end

  # update user
  def update(
        conn,
        %{"user" => %{
          "name" => _name,
          "password" => old_pass,
          "new_password" => "",
          "new_password_confirm" => "",
          "email" => _email
        } = params}
      ) do
    user = conn.assigns.current_user

    update_user(conn, user, old_pass, params)
  end

  def update(conn, %{"user" => %{
        "name" => _name,
        "password" => old_pass,
        "new_password" => new_pass,
        "new_password_confirm" => confirm_new_pass,
        "email" => _email
      } = params}) do
    user = conn.assigns.current_user

    case new_pass == confirm_new_pass do
      true ->
        update_user(conn, user, old_pass, Map.put(params, "password", new_pass))

      false ->
        conn
        |> put_flash(:error, "New password dont match with the password confirmation")
        |> render("edit.html", changeset: Accounts.change_user(user), user_id: user.id)
    end
  end
end

lib/fatex_web/views/user_view.ex
defmodule FatexWeb.UserView do
  use FatexWeb, :view
end

lib/fatex_web/templates/user/edit.html.eex
<section class="user-form">
<%= form_for @changeset, Routes.user_path(@conn, :update, @user_id), fn f -> %>
  <label class="title">
    Fatex
  </label>
  <label>
    <%= text_input f, :name, placeholder: "Nome" %>
  </label>

  <label>
    <%= text_input f, :email, placeholder: "Email" %>
  </label>

  <label>
    <%= password_input f, :password, placeholder: "Senha atual" %>
  </label>

  <label>
    <%= password_input f, :new_password, placeholder: "Nova senha" %>
  </label>

  <label>
    <%= password_input f, :new_password_confirm, placeholder: "Confirmar senha" %>
  </label>

  <%= submit "Atualizar" %>
<% end %>
  <button onclick="location.href='<%= FatexWeb.Router.Helpers.live_path(@conn, FatexWeb.HomeLive) %>'" type="button" class="button-warn">
     Cancelar
  </button>
</section>

lib/fatex_web/templates/user/new.html.eex
<section class="user-form">
<%= form_for @changeset, Routes.user_path(@conn, :create), [class: "user-form"], fn f -> %>
  <label class="title">
    Fatex
  </label>
  <label>
    <%= text_input f, :name, placeholder: "Nome" %>
  </label>

  <label>
    <%= text_input f, :email, placeholder: "Email" %>
  </label>

  <label>
    <%= password_input f, :password, placeholder: "Senha" %>
  </label>

  <%= submit "Criar" %>

  <button onclick="location.href='<%= FatexWeb.Router.Helpers.login_path(@conn, :new) %>'" type="button" class="button-warn">
     Cancelar
  </button>
<% end %>
</section>